#!/usr/bin/env bash

# fake uberspace commands for testing

subCat=$1           # web
subSubCat=$2        # domain / backend
subSubSubCat=$3     # list

if [[ "$subCat" = "web" ]]
then
    if [[ "$subSubCat" = "domain" ]]
    then
        if [[ "$subSubSubCat" = "list" ]]
        then
            cat "$(dirname "$0")/output_uberspace_web_domain_list.txt"
        fi
    elif [[ $subSubCat = "backend" ]]
    then
        if [[ "$subSubSubCat" = "list" ]]
        then
            cat "$(dirname "$0")/output_uberspace_web_backend_list.txt"
        fi
    fi
fi