= SpaceUp Server
thraax.session@iatlas.technology

SpaceUp is a "simple" server / client construct, which helps provide or do actions on your webhost. Or just simplify things without using ssh/console.
It does as much possible without even a database (only saving credentials / install process), to keep it easy as possible.

== Features

* Adding/Deleting domains
* Start/Stop/Restart services
* Inspecting logfiles of the corresponding service
* Have a look on the space
* Future feature: You can write your own (automation) script (*.sus) to even more simplify jobs and stuff.
Like updating a piece of software. And this script will be automatically available as REST service and visible in the app! Cool, right? 😁

== Build & Run

Explain what it requires and how to build the project.
This project requires Java 8 (min) and you can build it executing the following command:

[source,console]
----
./gradlew build
java -jar SpaceUp-{Version}-all.jar
***REMOVED*** Don't forget to create web backend to make it publish
----

After the first run, you have run the installation procedure which is also explained in the swagger-ui. (Only in dev mode)

See:

* https://<yourserver>:9090/swagger-ui
* https://<yourserver>:9090/redoc
* https://<yourserver>:9090/rapidoc

== Architecture

The SpaceUp Server can run locally or directly on Uberspace and will open SSH channel to Uberspace.

[plantuml, architecture-diagram, svg, opts=inline]
----
package "Client side" {
    [SpaceUp Client] <-> HTTP
}

package "Local or Uberspace Server" {
    SSH <-left-> [SpaceUp Server] : Remote scripts
    HTTP <-left-> [SpaceUp Server]
}

cloud {
    SSH <-right-> [Uberspace] : ""
    [Infrastruktur] <-left- [Uberspace] : Uberspace Commands
}
----

//== Implementation
//Remember you can include piece of code extracted from your project using the `include` directive
//include::{sourcedir}/com/mycompany/service/MyService.java[tags=init]

//
//Example
//----
//include::../../main/kotlin/technology/iatlas/spaceup/Application.kt[]
//----