= SpaceUp Server
thraax.session@iatlas.technology

== Asciidoc Themes
If you want to use another theme. Replace theme-name: {data-baseurl}/?theme={theme-name}

.Click me to open Themes
[%collapsible]
====
{data-themes}
====

== Description

SpaceUp is a "simple" server / client construct, which helps provide or do actions on your webhost. Or just simplify things without using ssh/console.
It does as much possible without a database (only saving credentials / install process), to keep it easy as possible.

The server application is written in kotlin with micronaut as web framework. The client is written in Dart with Flutter as framework.

== Features

* Adding/Deleting domains
* Start/Stop/Restart services
* Inspecting logfiles of the corresponding service
* Have a look on the space

* Other features which are planned:
** Handle web backends (uberspace web commands)
** Handle mail (uberspace mail commands)
** Add/Delete services with internal editor
** Support GraalVM as native application for smaller footprint
** Migrating to JVM 11 =< x
** Self-Updating JAR (Never download it by yourself again!)
** Write your own (automation) script (*.sus) to even more simplify jobs and stuff.
Like updating a piece of software. And this script will be automatically available as REST service and visible in the app! Cool, right? ðŸ˜
** ... and so on.

If any other feature is wished, write me a small email, so I will register you for youtrack to open an issue:
*thraax.session@iatlas.technology*

Little big bonus: There is a multiplatform app (written in Flutter) which already consumes the APIs. ðŸ˜
You should know it's not tested with ios/osx as I am not an apple user.
But it works for Web, Android, Windows and soon Linux.

== Code Repo / Bug tracker / etc.

I've of course my own tool infrastructure where I keep my code and bugs in place.

Git: https://git.iatlas.dev/SpaceUp

Youtrack: https://yt.iatlas.dev/articles/SU-A-1/Preamble

Artifactory:
https://artifactory.iatlas.dev/#browse/browse:technology.iatlas.spaceup:technology%2Fiatlas%2Fspaceup%2FSpaceUp

Youtrack is mainly for bug tracking but also a little knowledgebase.
But the main documentation will be here in Asciidoc which will be regularly updated.

== Build & Run

=== Server application

Requirements:

* Java 8

The application itself is a fatjar which can be directly executed.

[console]
----
# Build the jar file
./gradlew assemble

#
# The parameters are necessary for now.
# Later they will be used from the installation process.
#

# Normal prod usecase
java -jar target/lib/SpaceUp-{Version}-all.jar -micronaut.server.host=0.0.0.0 -micronaut.host.port=<Your Port>

# In dev you can directly supply SSH configuration when you pass "-spaceup.dev.ssh.db-credentials=true"
# Default is '-spaceup.dev.ssh.db-credentials=false'
# If you've got troubles, increase loglevel with '-spaceup.logging.level=DEBUG'
java -jar target/lib/SpaceUp-{Version}-all.jar -micronaut.server.host=127.0.0.1 -micronaut.host.port=<Your Port> -spaceup.ssh.host=<Your server to connect> -spaceup.ssh.username=<User> -spaceup.ssh.password=<Password>
----

Don't forget to create the uberspace web backend to make it external visible for the client. ðŸ˜‰

*After the first run, you have run the installation procedure* which is also explained in the swagger-ui.
Swaager-ui, redoc and rapidoc are only available in dev mode as they are normally not necessary to finish the installation.
In the near time I will adapt the app which helps you to finish the set up SpaceUp.

See:

* {data-baseurl}/swagger-ui
* {data-baseurl}/redoc
* {data-baseurl}/rapidoc

After first startup you will be greeted with this console output.
*Beware the output of they API Key, which you need to verify that it is you, when you finish the installation!*

[console]
----
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.2.4)

11:13:10.693 [main] INFO  io.micronaut.context.env.DefaultEnvironment - Established active environments: [prod]
2022-01-07 11:13:10,697 main DEBUG AsyncLogger.ThreadNameStrategy=UNCACHED (user specified null, default is UNCACHED)
2022-01-07 11:13:10,697 main DEBUG org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
   â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ    â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„    â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ    â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ    â–ˆâ–„     â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–„
  â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ
  â–ˆâ–ˆâ–ˆ    â–ˆâ–€    â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ    â–ˆâ–€    â–ˆâ–ˆâ–ˆ    â–ˆâ–€  â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ
  â–ˆâ–ˆâ–ˆ          â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ         â–„â–ˆâ–ˆâ–ˆâ–„â–„â–„     â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ
â–€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–€  â–€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ        â–€â–€â–ˆâ–ˆâ–ˆâ–€â–€â–€     â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–€â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–€
         â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ          â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ    â–ˆâ–„    â–ˆâ–ˆâ–ˆ    â–ˆâ–„  â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ
   â–„â–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ          â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆ    â–ˆâ–ˆâ–ˆ   â–ˆâ–ˆâ–ˆ
 â–„â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–€   â–„â–ˆâ–ˆâ–ˆâ–ˆâ–€        â–ˆâ–ˆâ–ˆ    â–ˆâ–€  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–€    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–€   â–„â–ˆâ–ˆâ–ˆâ–ˆâ–€
	SpaceUp Server (0.0.20-SNAPSHOT)
11:13:12.050 [main] INFO  technology.iatlas.spaceup.core.startup.StartupEventListener - Running SpaceUp startup
11:13:12.050 [main] DEBUG technology.iatlas.spaceup.core.startup.StartupEventListener - OS: Linux
11:13:12.050 [main] INFO  technology.iatlas.spaceup.core.startup.StartupEventListener - Create remote directories
11:13:12.053 [main] INFO  technology.iatlas.spaceup.core.startup.StartupEventListener - Create /home/gino/.spaceup
11:13:12.060 [main] INFO  technology.iatlas.spaceup.core.startup.StartupEventListener - Create /home/gino/.spaceup/tmp
11:13:12.062 [main] INFO  technology.iatlas.spaceup.services.DbService - Init DB @ /home/gino/.spaceup/spaceup.db
11:13:12.367 [main] INFO  technology.iatlas.spaceup.services.DbService - Created and migrated DB
11:13:12.367 [main] INFO  technology.iatlas.spaceup.services.DbService - Indexing fields ...
11:13:12.721 [main] INFO  technology.iatlas.spaceup.core.startup.StartupEventListener - Seems to be first run. Set not installed!
11:13:12.726 [main] INFO  technology.iatlas.spaceup.core.startup.StartupEventListener - Finish installation with API key: IvTX3L4b
11:13:12.732 [main] INFO  technology.iatlas.spaceup.core.startup.StartupEventListener - Finished SpaceUp startup
11:13:12.823 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 2456ms. Server Running: http://localhost:9090
----

=== Client application

I'll upload regular the client apps here:
https://artifactory.iatlas.dev/#browse/browse:spaceup-client

But if you like to build it by your own, go ahead with the following!

Requirements:

* Flutter (current version)
* ADB (if you want to install it directly on your Android phone)

[console]
----
# platform: apk, web, windows and etc.
flutter build <platform> --no-sound-null-safety
----

Afterwards you can find it here:
----
<your-directory>\SpaceUp-UI\spaceup_ui\build\windows\runner\Release
----

== Architecture

The SpaceUp Server can run locally or directly on Uberspace and will open SSH channel to Uberspace / to local SSHD.

=== The Big Picture

[plantuml, architecture-diagram, svg, opts=inline]
----
!pragma layout smetana

package "Client side" {
    [SpaceUp Client] <-> HTTP : "CRUD"
}

package "Local or Uberspace Server" {
    SSH <-left-> [SpaceUp Server] : Remote scripts
    HTTP <-left-> [SpaceUp Server] : "API Endpoints"
    [SpaceUp Server] <-up-> NoSQL_DB
}

cloud {
    SSH <-right-> [Uberspace] : ""
    [Infrastruktur] <-left- [Uberspace] : Uberspace Commands
}
----

//== Implementation
//Remember you can include piece of code extracted from your project using the `include` directive
//include::{sourcedir}/com/mycompany/service/MyService.java[tags=init]

//
//Example
//----
//include::../../main/kotlin/technology/iatlas/spaceup/Application.kt[]
//----