= SpaceUp Server
thraax.session@iatlas.technology

SpaceUp is a "simple" server / client construct, which helps provide or do actions on your webhost. Or just simplify things without using ssh/console.
It does as much possible without even a database, to keep it easy as possible.

== Features

* Adding/Deleting domains
* Start/Stop/Restart services
* Inspecting logfiles of the corresponding service
* Have a look on the space
* Future feature: You can write your own (automation) script (*.sus) to even more simplify jobs and stuff. Like updating a piece of software. And this script will be automatically available as REST service and visible in the app! Cool, right? ðŸ˜

== Build & Run

Explain what it requires and how to build the project. For example:

This project requires Java 8 (min) and you can build it executing the following command:

[source,console]
----
./gradlew build
java -jar SpaceUp-{Version}-all.jar
# Don't forget to create web backend to make it publish
----

== Architecture

When you document your architecture you can use different `diagrams` blocks as
for example `plantuml`

[plantuml]
----
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----

== Implementation

Remember you can include piece of code extracted from your project using the `include` directive

    include::{sourcedir}/com/mycompany/service/MyService.java[tags=init]

Example
----
include::../../main/kotlin/technology/iatlas/spaceup/Application.kt[]
----